[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = [
    'python3.9 -m venv venv',
    '. venv/bin/activate',
    'pip install --upgrade pip setuptools wheel',
    'pip install --no-cache-dir -r requirements.txt'
]

[phases.build]
cmds = [
    'mkdir -p storage/images storage/temp storage/models storage/embeddings storage/logs',
    'chmod -R 755 storage/',
    'ls -la storage/ || echo "Storage directory check"'
]

[start]
cmd = '. venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT'