[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = [
    'python3.9 -m venv venv',
    '. venv/bin/activate',
    'pip install --upgrade pip setuptools wheel',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'mkdir -p storage/{images,temp,models,embeddings,logs}',
    'chmod -R 755 storage/'
]

[start]
cmd = '. venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT'